### ISSUE TITLE
Changing the project name and firebase database with my own

### ISSUE THREAD

**Issue by MustafaYagcioglu** [Bruno-Furtado/fastbuy-app#31]
The code worked as is, however, if I delete android and ios folders, recreate them with "react-native eject" command (with relocating original google-services.json in android/app), I get error at runtime.

As the second issue, if I want to change firebase database with my own one, again I get similar errors.

For the new developers, a guideline for rebuilding project with the developers own application name and id (for play store), and own firebase database will be very helpful for developers to start development and add new features to source code.    

For my case; Development OS: Linux, target OS:android

Best Regards,

**Comment by MustafaYagcioglu** [comment]
**Describe the bug**
A clear and concise description of what the bug is.

**Steps to reproduce the behavior:**
1. I've downloaded the fastbuy stable version and run it on android device successfully.
2. I changed the "fastbuy" terms to "myfastbuy" in following files;
android/app/BUCK
android/app/build.gradle
android/app/source/main/AndroidManifest.xml
android/..../MainActivity.java
android/..../MainApplication.java
3. Build code successfully with android studio.
4. On terminal, run "react-native run-android".
5. Program run successfully, however I've got "Could not log in, Try again later" warning.
6. It could be expected, because a new app is trying to reach fastbuy firebase database, so I have to create my own database
7. On firebase console, I added a new project, copy google-services.json to android/app folder instead of the current one. 
8. At firebase console settings, I enabled Google sign-in method.
9. On terminal, run react-native run-android.

**Expected behavior:**
At this time I expected program to run successfully and can log in successfully to my database. However, program started successfully but again when trying to login, got "Could not log in, Try again later" warning again.

**Screenshots:**
![image](https://user-images.githubusercontent.com/46642735/51086191-73436880-1754-11e9-8ed8-996c6da9dce8.png)


**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04

**Smartphone (please complete the following information):**
 - Device: Lenovo K6 Note
 - OS: Android 7.0

**Comment by Bruno-Furtado** [comment]
@MustafaYagcioglu, thanks for description.

Would you generate a specific SHA-1 fingerprint for your app? It's necessary for Google Sign In.

You can check more on:
[Authenticate Using Google Sign-In on Android](https://firebase.google.com/docs/auth/android/google-signin) (specially the step 4).

**Comment by MustafaYagcioglu** [comment]
Dear Bruno, thanks for the fast response. 
I generated it as SHA1: 3E:27:.....:A3:AD:42:64:D5  and added it to firebase console. However, same problem continues.
I recognized that SHA1 is same with the one that I generated with original fastbuy source code. Is it normal?

**Comment by Bruno-Furtado** [comment]
@MustafaYagcioglu, could you debug?

**Comment by MustafaYagcioglu** [comment]
I debugged but couldn't find a solution. This weekend, I am planning to re-debug and report the situation. Regards.

**Comment by MustafaYagcioglu** [comment]
Dear @Bruno-Furtado , I am getting the error below from the logcat. I googled it and tried many things but couldn't find a solution.
--I updated debug.keystore, created a different SHA-1 key.
--I updated firebase console, created google-services.json again.
Do you have any hint for the solution?
Regards.
 
2019-01-20 13:40:06.671 21674-21674/me.furtado.fastbuy E/RNFirebaseAuth: signInWithCredential:onComplete:failure
    com.google.firebase.FirebaseException: An internal error has occurred. [ Invalid Idp Response:access_token audience is not for this project ]
        at com.google.firebase.auth.api.internal.zzds.zzb(Unknown Source)
        at com.google.firebase.auth.api.internal.zzew.zza(Unknown Source)
        at com.google.firebase.auth.api.internal.zzeo.zzc(Unknown Source)
        at com.google.firebase.auth.api.internal.zzep.onFailure(Unknown Source)
        at com.google.firebase.auth.api.internal.zzdy.dispatchTransaction(Unknown Source)
        at com.google.android.gms.internal.firebase_auth.zzb.onTransact(Unknown Source)
        at android.os.Binder.execTransact(Binder.java:565)

**Comment by MustafaYagcioglu** [comment]
To prevent some confusion, I canceled to changes related to "myfastbuy" from "fastbuy". I used fastbuy as is, only changed the version to "1.1.1" from "1.1" in package.json file

**Comment by MustafaYagcioglu** [comment]
@Bruno-Furtado ,
The problem was related with the Step 3 - Setup certificate fingerprint
1. Delete debug.keystore in .android folder.
2. Generate debug.keystore with command:
keytool -genkey -v -keystore ~/.android/debug.keystore -storepass android -alias androiddebugkey -keypass android -dname "CN=Android Debug,O=Android,C=US" -keyalg RSA -keysize 2048 -validity 10000
"-keysize 2048" option was critical because without it, Android Studio build failed with "The security strength of SHA-1 digest algorithm is not sufficient for this key size" error.
3. For the newbies like me, do not forget to copy .android/debug.keystore to fastbuy-app/android/keystores.

Thanks for the support. 
Best Regards.
